'use client';

import '@/styles/globals.css';

import { usePathname } from 'next/navigation';
import { useEffect, useState } from 'react';
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';


export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    const pathname = usePathname();
    const [isAdminPage, setIsAdminPage] = useState(pathname.startsWith('/admin'));
    useEffect(() => {

    }, []);
    return (
        <html>
            <body>
                {!isAdminPage && <Navbar />}
                {children}
                {!isAdminPage && <Footer />}
            </body>
        </html>
    )
}

/*
export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
}
*/