import '@/styles/globals.css';

import { usePathname } from 'next/navigation';
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';
import { useState, useEffect } from 'react';

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    const pathname = usePathname();
    const [isAdminPage, setIsAdminPage] = useState(pathname.startsWith('/admin'));

    useEffect(() => {
        setIsAdminPage(pathname.startsWith('/admin'));
    }, [pathname]);

    return (
        <html>
            <body>
                {!isAdminPage && <Navbar />}
                {children}
                {!isAdminPage && <Footer />}
            </body>
        </html>
    )
}

/*
export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
}
*/